# Generated by Django 5.2.5 on 2025-12-13 19:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_bn',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Author (Bangla)'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_bn',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description (Bangla)'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_bn',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Publisher (Bangla)'),
        ),
        migrations.AddField(
            model_name='book',
            name='short_description_bn',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Short Description (Bangla)'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_bn',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Book Title (Bangla)'),
        ),
    ]
