# Generated by Django 5.2.5 on 2025-12-07 18:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_slug_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='BookStore', max_length=200, verbose_name='Site Name')),
                ('tagline', models.CharField(blank=True, max_length=300, null=True, verbose_name='Tagline')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_settings/', verbose_name='Site Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_settings/', verbose_name='Favicon')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='site_settings/', verbose_name='Footer Logo')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Phone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Physical Address')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube URL')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta Keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author_bn',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Author (Bangla)'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_bn',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description (Bangla)'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_bn',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Publisher (Bangla)'),
        ),
        migrations.AddField(
            model_name='book',
            name='short_description_bn',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Short Description (Bangla)'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_bn',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Book Title (Bangla)'),
        ),
    ]
