# Generated by Django 5.2.5 on 2025-12-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_sitesettings_book_author_bn_book_description_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(blank=True, help_text='e.g., "All rights reserved" or custom text', max_length=200, null=True, verbose_name='Copyright Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title for homepage', max_length=200, null=True, verbose_name='Meta Title'),
        ),
    ]
