# Generated by Django 5.2.5 on 2025-12-07 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_quicklink'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('menu_type', models.CharField(choices=[('single', 'Single Menu'), ('dropdown', 'Dropdown Menu')], default='single', max_length=20, verbose_name='Menu Type')),
                ('url', models.CharField(blank=True, help_text='Required for single menu, optional for dropdown parent', max_length=500, null=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('open_new_tab', models.BooleanField(default=False, verbose_name='Open in New Tab')),
                ('icon_class', models.CharField(blank=True, help_text='e.g., fas fa-home', max_length=100, null=True, verbose_name='Icon Class')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='books.navmenu', verbose_name='Parent Menu')),
            ],
            options={
                'verbose_name': 'Navigation Menu',
                'verbose_name_plural': 'Navigation Menus',
                'ordering': ['order', 'display_name'],
            },
        ),
    ]
