# Generated by Django 5.2.5 on 2025-12-07 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_navmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='navmenu',
            name='link_type',
            field=models.CharField(choices=[('url', 'Custom URL'), ('category', 'Category'), ('book', 'Book')], default='url', max_length=20, verbose_name='Link Type'),
        ),
        migrations.AddField(
            model_name='navmenu',
            name='linked_book',
            field=models.ForeignKey(blank=True, help_text='For book link type', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Linked Book'),
        ),
        migrations.AddField(
            model_name='navmenu',
            name='linked_category',
            field=models.ForeignKey(blank=True, help_text='For category link type', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.category', verbose_name='Linked Category'),
        ),
        migrations.AlterField(
            model_name='navmenu',
            name='url',
            field=models.CharField(blank=True, help_text='For custom URL type', max_length=500, null=True, verbose_name='Custom URL'),
        ),
    ]
