# Generated by Django 4.2.7 on 2025-11-08 22:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rental Price')),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Security Deposit')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('rental_date', models.DateTimeField(auto_now_add=True, verbose_name='Rental Date')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual Return Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Late Fee')),
                ('late_days', models.IntegerField(default=0, verbose_name='Days Late')),
                ('renewal_count', models.IntegerField(default=0, verbose_name='Times Renewed')),
                ('can_renew', models.BooleanField(default=True, verbose_name='Can Renew')),
                ('customer_notes', models.TextField(blank=True, null=True, verbose_name='Customer Notes')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='books.book')),
            ],
            options={
                'verbose_name': 'Book Rental',
                'verbose_name_plural': 'Book Rentals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration (Days)')),
                ('price_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of book price to charge (e.g., 10 for 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Price Percentage of Book Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rental Plan',
                'verbose_name_plural': 'Rental Plans',
                'ordering': ['order', 'days'],
            },
        ),
        migrations.CreateModel(
            name='RentalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_deposit_percentage', models.DecimalField(decimal_places=2, default=20, help_text='Percentage of book price to hold as security deposit', max_digits=5, verbose_name='Security Deposit Percentage')),
                ('daily_late_fee', models.DecimalField(decimal_places=2, default=10, help_text='Amount charged per day for overdue rentals', max_digits=10, verbose_name='Daily Late Fee (BDT)')),
                ('max_active_rentals_per_user', models.IntegerField(default=5, help_text='Maximum number of active rentals a user can have', verbose_name='Max Active Rentals Per User')),
                ('max_renewals', models.IntegerField(default=3, help_text='Maximum number of times a rental can be renewed', verbose_name='Max Renewals')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='Enable Notifications')),
                ('due_soon_days', models.IntegerField(default=3, verbose_name='Due Soon Notification (Days)')),
                ('min_stock_for_rental', models.IntegerField(default=1, help_text='Minimum stock quantity required to allow rental', verbose_name='Minimum Stock for Rental')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rental Settings',
                'verbose_name_plural': 'Rental Settings',
            },
        ),
        migrations.CreateModel(
            name='RentalStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='rentals.bookrental')),
            ],
            options={
                'verbose_name': 'Rental Status History',
                'verbose_name_plural': 'Rental Status Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_condition_rating', models.IntegerField(help_text='Rate the condition of the book you received', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Book Condition Rating (1-5)')),
                ('service_rating', models.IntegerField(help_text='Rate our rental service', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Service Rating (1-5)')),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Overall Rating (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Your Feedback')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='Admin Response')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_feedbacks', to='books.book')),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='rentals.bookrental')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental Feedback',
                'verbose_name_plural': 'Rental Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bookrental',
            name='rental_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.rentalplan'),
        ),
        migrations.AddField(
            model_name='bookrental',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RentalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('rental_confirmed', 'Rental Confirmed'), ('rental_active', 'Rental Active'), ('due_soon', 'Due Soon (3 days)'), ('due_tomorrow', 'Due Tomorrow'), ('overdue', 'Overdue'), ('returned', 'Returned'), ('renewal_confirmed', 'Renewal Confirmed'), ('feedback_request', 'Feedback Request')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rentals.bookrental')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental Notification',
                'verbose_name_plural': 'Rental Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='rentals_ren_user_id_98e1d0_idx'), models.Index(fields=['rental', 'notification_type'], name='rentals_ren_rental__93f8dc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bookrental',
            index=models.Index(fields=['user', 'status'], name='rentals_boo_user_id_d5521c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookrental',
            index=models.Index(fields=['book', 'status'], name='rentals_boo_book_id_a04da0_idx'),
        ),
        migrations.AddIndex(
            model_name='bookrental',
            index=models.Index(fields=['due_date'], name='rentals_boo_due_dat_df10b1_idx'),
        ),
    ]
