# Generated by Django 4.2.7 on 2025-11-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalsettings',
            name='max_active_rentals_per_user',
            field=models.IntegerField(default=3, help_text='Maximum number of active rentals a user can have at the same time', verbose_name='Max Active Rentals Per User'),
        ),
    ]
