# Generated by Django 5.2.5 on 2025-11-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rentalsettings_max_active_rentals_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrental',
            name='admin_notes_bn',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Notes (Bangla)'),
        ),
        migrations.AddField(
            model_name='bookrental',
            name='customer_notes_bn',
            field=models.TextField(blank=True, null=True, verbose_name='Customer Notes (Bangla)'),
        ),
        migrations.AddField(
            model_name='rentalplan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Plan Description'),
        ),
        migrations.AddField(
            model_name='rentalplan',
            name='description_bn',
            field=models.TextField(blank=True, null=True, verbose_name='Plan Description (Bangla)'),
        ),
        migrations.AddField(
            model_name='rentalplan',
            name='name_bn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan Name (Bangla)'),
        ),
    ]
