# Generated by Django 5.2.5 on 2025-12-13 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_author_bn_book_description_bn_book_publisher_bn_and_more'),
        ('rentals', '0003_bookrental_admin_notes_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalplan',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='rental_plans', to='books.book', verbose_name='Available Books'),
        ),
        migrations.AlterField(
            model_name='rentalplan',
            name='price_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='This field is no longer used. Pricing is now: 10 + (2 × days)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Price Percentage of Book Price (Legacy)'),
        ),
        migrations.AlterField(
            model_name='rentalsettings',
            name='daily_late_fee',
            field=models.DecimalField(decimal_places=2, default=3, help_text='Amount charged per day for overdue rentals', max_digits=10, verbose_name='Daily Late Fee (BDT)'),
        ),
    ]
