# Generated by Django 5.2.5 on 2025-12-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rentalplan_books_alter_rentalplan_price_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalsettings',
            name='security_deposit_percentage',
        ),
        migrations.AddField(
            model_name='rentalsettings',
            name='security_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Flat security deposit amount per user (one-time, not per book)', max_digits=10, verbose_name='Security Deposit Amount (BDT)'),
        ),
    ]
