# Generated by Django 5.2.5 on 2025-12-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_remove_rentalsettings_security_deposit_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalsettings',
            name='base_rental_fee',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Base fee charged for any rental (regardless of duration)', max_digits=10, verbose_name='Base Rental Fee (BDT)'),
        ),
        migrations.AddField(
            model_name='rentalsettings',
            name='per_day_rental_fee',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Additional fee charged per day of rental', max_digits=10, verbose_name='Per Day Rental Fee (BDT)'),
        ),
    ]
