# Generated by Django 5.2.5 on 2025-12-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_line1_bn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1 (Bangla)'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_line2_bn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2 (Bangla)'),
        ),
        migrations.AddField(
            model_name='address',
            name='city_bn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City (Bangla)'),
        ),
        migrations.AddField(
            model_name='address',
            name='full_name_bn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name (Bangla)'),
        ),
        migrations.AddField(
            model_name='address',
            name='state_bn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Division (Bangla)'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name_bn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name (Bangla)'),
        ),
    ]
