# Generated by Django 4.2.7 on 2025-11-09 17:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enable Chat Widget')),
                ('welcome_message', models.TextField(default='Hello! How can we help you today?', verbose_name='Welcome Message')),
                ('welcome_message_bn', models.TextField(default='আসসালামু আলাইকুম, রকমারি উটকসে স আপনাকে স্বাগতম। অনুগ্রহ করে জানাবেন কিভাবে সহযোগিতা করতে পারি।', verbose_name='Welcome Message (Bengali)')),
                ('offline_message', models.TextField(default="We're currently offline. Please leave a message.", verbose_name='Offline Message')),
                ('offline_message_bn', models.TextField(default='আমরা এই মুহূর্তে অফলাইনে আছি। অনুগ্রহ করে একটি বার্তা রেখে যান।', verbose_name='Offline Message (Bengali)')),
                ('widget_position', models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left')], default='bottom-right', max_length=20, verbose_name='Widget Position')),
                ('primary_color', models.CharField(default='#008B8B', max_length=7, verbose_name='Primary Color')),
                ('auto_assign', models.BooleanField(default=True, verbose_name='Auto Assign to Agent')),
                ('max_file_size', models.IntegerField(default=5, verbose_name='Max File Size (MB)')),
                ('business_hours_start', models.TimeField(default='09:00', verbose_name='Business Hours Start')),
                ('business_hours_end', models.TimeField(default='18:00', verbose_name='Business Hours End')),
                ('show_online_status', models.BooleanField(default=True, verbose_name='Show Online Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Settings',
                'verbose_name_plural': 'Chat Settings',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20, verbose_name='Priority')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('user_unread_count', models.IntegerField(default=0, verbose_name='User Unread Count')),
                ('agent_unread_count', models.IntegerField(default=0, verbose_name='Agent Unread Count')),
                ('last_message_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Message At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_bn', models.CharField(blank=True, max_length=100, verbose_name='Title (Bengali)')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_bn', models.TextField(blank=True, verbose_name='Content (Bengali)')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quick Reply',
                'verbose_name_plural': 'Quick Replies',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SupportAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('display_name_bn', models.CharField(blank=True, max_length=100, verbose_name='Display Name (Bengali)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='support/agents/', verbose_name='Avatar')),
                ('is_online', models.BooleanField(default=False, verbose_name='Is Online')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('bio_bn', models.TextField(blank=True, verbose_name='Bio (Bengali)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Last Seen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Agent',
                'verbose_name_plural': 'Support Agents',
                'ordering': ['order', '-is_online', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_agent', models.BooleanField(default=False, verbose_name='Is Agent Message')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('system', 'System')], default='text', max_length=20, verbose_name='Message Type')),
                ('content', models.TextField(verbose_name='Content')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'txt'])], verbose_name='Attachment')),
                ('attachment_name', models.CharField(blank=True, max_length=255, verbose_name='Attachment Name')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Is Edited')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Edited At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to='support.supportagent'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
