# Generated by Django 4.2.7 on 2025-11-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversion_notes',
            field=models.TextField(blank=True, verbose_name='Conversion Notes'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_converted',
            field=models.BooleanField(default=False, verbose_name='Converted to Sale'),
        ),
    ]
