# Generated by Django 5.2.5 on 2025-12-07 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_coupon_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Gift City',
                'verbose_name_plural': 'Gift Cities',
            },
        ),
        migrations.CreateModel(
            name='GiftOccasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Gift Occasion',
                'verbose_name_plural': 'Gift Occasions',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='description_bn',
            field=models.TextField(blank=True, help_text='Description of the coupon (Bangla)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notes_bn',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Notes (Bangla)'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_notes_bn',
            field=models.TextField(blank=True, null=True, verbose_name='Customer Notes (Bangla)'),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_deliver_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_from_alt_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_from_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_from_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_message_bn',
            field=models.TextField(blank=True, null=True, verbose_name='Gift Message (Bangla)'),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_occasion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_gift',
            field=models.BooleanField(default=False, help_text='Whether this order should be treated as a gift'),
        ),
        migrations.CreateModel(
            name='GiftArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='orders.giftcity')),
            ],
            options={
                'verbose_name': 'Gift Area',
                'verbose_name_plural': 'Gift Areas',
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GiftZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='orders.giftarea')),
            ],
            options={
                'verbose_name': 'Gift Zone',
                'verbose_name_plural': 'Gift Zones',
                'unique_together': {('area', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GiftForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gift', models.BooleanField(default=True)),
                ('from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('from_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('from_alt_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('to_name', models.CharField(blank=True, max_length=255, null=True)),
                ('to_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('to_address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('to_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('deliver_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.giftarea')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.giftcity')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_forms', to='orders.order')),
                ('occasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.giftoccasion')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.giftzone')),
            ],
            options={
                'verbose_name': 'Gift Form',
                'verbose_name_plural': 'Gift Forms',
                'ordering': ['-created_at'],
            },
        ),
    ]
