# Generated by Django 5.2.5 on 2025-12-26 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_giftarea_giftcity_giftoccasion_coupon_description_bn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(help_text='City name in English (case-insensitive matching)', max_length=100, unique=True)),
                ('city_name_bn', models.CharField(blank=True, help_text='City name in Bangla (optional)', max_length=100, null=True, verbose_name='City Name (Bangla)')),
                ('fee', models.DecimalField(decimal_places=2, help_text='Shipping fee amount in BDT', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_default', models.BooleanField(default=False, help_text='Mark as default fee for cities not in the list (only one can be default)')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this shipping fee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Fee',
                'verbose_name_plural': 'Shipping Fees',
                'ordering': ['city_name'],
                'indexes': [models.Index(fields=['city_name'], name='orders_ship_city_na_a5a6ba_idx'), models.Index(fields=['is_default', 'is_active'], name='orders_ship_is_defa_c56394_idx')],
            },
        ),
    ]
